// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBei3BMDeZrUVBAGe8UFlncAYIlFjIqlSY',
    appId: '1:265726670021:web:078bd2c5d1e2cc4a0a6cac',
    messagingSenderId: '265726670021',
    projectId: 'tbt-app-42f0a',
    authDomain: 'tbt-app-42f0a.firebaseapp.com',
    storageBucket: 'tbt-app-42f0a.firebasestorage.app',
    measurementId: 'G-VKF9K14KQC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCMoMg541MwV5Pu7SnTV3DxcY9lHibyroE',
    appId: '1:265726670021:android:47fac21aaec6357a0a6cac',
    messagingSenderId: '265726670021',
    projectId: 'tbt-app-42f0a',
    storageBucket: 'tbt-app-42f0a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAH8X0Zsoy7nFj56ZaPHa9qgt2ptiO-6rU',
    appId: '1:265726670021:ios:66b23fb241492a280a6cac',
    messagingSenderId: '265726670021',
    projectId: 'tbt-app-42f0a',
    storageBucket: 'tbt-app-42f0a.firebasestorage.app',
    iosBundleId: 'com.tamilbusinesstribe.tbtApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAH8X0Zsoy7nFj56ZaPHa9qgt2ptiO-6rU',
    appId: '1:265726670021:ios:66b23fb241492a280a6cac',
    messagingSenderId: '265726670021',
    projectId: 'tbt-app-42f0a',
    storageBucket: 'tbt-app-42f0a.firebasestorage.app',
    iosBundleId: 'com.tamilbusinesstribe.tbtApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBei3BMDeZrUVBAGe8UFlncAYIlFjIqlSY',
    appId: '1:265726670021:web:d7ab6137192a506f0a6cac',
    messagingSenderId: '265726670021',
    projectId: 'tbt-app-42f0a',
    authDomain: 'tbt-app-42f0a.firebaseapp.com',
    storageBucket: 'tbt-app-42f0a.firebasestorage.app',
    measurementId: 'G-DV63RSBGMR',
  );
}
