default_platform(:ios)

platform :ios do
  desc "Upload a new build to TestFlight"
  lane :beta do
    api_key = app_store_connect_api_key(
      key_id:      ENV["APPLE_API_KEY_ID"],
      issuer_id:   ENV["APPLE_API_ISSUER_ID"],
      key_content: ENV["APPLE_API_KEY_CONTENT"],
      in_house:    false,
    )

    upload_to_testflight(
      api_key:                          api_key,
      ipa:                              "../build/ios/ipa/tbt_app.ipa",
      skip_waiting_for_build_processing: true,
      changelog:                        ENV.fetch("RELEASE_NOTES", ""),
    )
  end
end
